#test12345
os: linux
dist: focal
language: shell
#install: skip
#check3
script:
  - sudo apt-get update -qq  # Update package lists quietly
  - sudo apt-get install -y -qq btrfs-progs
#Initiaiting build as a collaborator -2
